### ISSUE TITLE
TOO CHARMING

### ISSUE THREAD

**Issue by dxu** [judytrinh/Charms#1]
![](http://media.tumblr.com/eb16b8a790e41803c8c53c6a80a7aace/tumblr_inline_nbm9a65Ysh1sld37j.gif)

**Comment by dxu** [comment]
sorry i didn't get the chance to address this, PR in progress

**Comment by ericslee** [comment]
@dxu is her nose bleeding in that gif <_<

**Comment by dxu** [comment]
lul this gif
